# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cab1ae11be9b98b26e39645080e5df81854a0643444013febdc269613b881d3b9b57b665cf8ce3c90f110ad886161e6bb4701ab20afc1844e7743aaea3af3b9f

test:
  secret_key_base: 27bff9b7cf0c5a197772e1c7c7e6b5ae6b9afc0edefed220439a487f22e6ae070701fff31331a53179ea1dcc3a2c487208e0c2b03b584960c6a72587444d15fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
